# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/default.png'

# Special
background='#1b1b1e'
foreground='#dcd0d5'
cursor='#dcd0d5'

# Colors
color0='#1b1b1e'
color1='#384457'
color2='#4E586E'
color3='#565464'
color4='#965D6A'
color5='#636F88'
color6='#AB9AA7'
color7='#dcd0d5'
color8='#9a9195'
color9='#384457'
color10='#4E586E'
color11='#565464'
color12='#965D6A'
color13='#636F88'
color14='#AB9AA7'
color15='#dcd0d5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
