# Shell variables
# Generated by 'wal'
wallpaper='/home/weeb/.local/share/backgrounds/2023-11-06-13-15-02-default.png'

# Special
background='#1f1b16'
foreground='#f2e0cc'
cursor='#f2e0cc'

# Colors
color0='#1f1b16'
color1='#CB7359'
color2='#C08C5D'
color3='#DE9870'
color4='#948082'
color5='#B1968F'
color6='#E7AF91'
color7='#f2e0cc'
color8='#a99c8e'
color9='#CB7359'
color10='#C08C5D'
color11='#DE9870'
color12='#948082'
color13='#B1968F'
color14='#E7AF91'
color15='#f2e0cc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
