name: Build Nyarch ISO on commit

on:
  push:
    branches:
      - main
      - nvidia
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.editorconfig'
      - '**.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'PKGBUILD'
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: find .
      - run: cat /etc/os-release
      - run: pacman-key --init
      - run: pacman --noconfirm -Sy archlinux-keyring grub
      - run: bash Gnome/install_chaotic.sh
      - run: cd Gnome && bash steps.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Nyarch Linux Live ISO
          path: /__w/NyarchLinux/NyarchLinux/Gnome/out/*.iso
